# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mast

  pod 'FMDB'
  # pod 'FMDB/FTS'   # FMDB with FTS
  # pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
  # pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
  # pod 'FMDB/SQLCipher'   # FMDB with SQLCipher

  pod 'AWSiOSSDKv2'
  
  target 'MastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MastUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
